FinalProject_Market/Areas/Admin/Models/ViewModels/AddProductViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FinalProject_Market.Models.ViewModels
{
    public class AddProductViewModel
    {
        [Display(Name = "نام محصول")]
        [Required]
        public string ProductName { get; set; }

        public decimal? Price { get; set; }

        public List<IFormFile>? fileImages { get; set; }
    }
}

FinalProject_Market/Areas/Seller/Controllers/ProductManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppCore.DtoModels.Category;
using AppCore.DtoModels.Product;
using AppService.Admin_;
using AutoMapper;
using FinalProject_Market.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FinalProject_Market.Areas.Admin.Controllers
{
    [Area("seller")]
    [Authorize(Roles = "seller")]
    public class ProductManagementController : Controller
    {
        #region field
        private readonly IAccountAppServices _account;
        private readonly IMapper _mapper;
        private readonly IProductAppService _productAppService;
        private readonly IPavilionAppService _pavilionAppService;
        private readonly IDirectOrderAppService _directOrderAppService;
        #endregion

        #region ctor
        public ProductManagementController(IAccountAppServices account,
            IMapper mapper, IProductAppService productAppService,
            IPavilionAppService pavilionAppService, IDirectOrderAppService directOrderAppService)
        {
            _account = account;
            _mapper = mapper;
            _productAppService = productAppService;
            _pavilionAppService = pavilionAppService;
            _directOrderAppService = directOrderAppService;
        }
        #endregion

        #region Implementation
        // GET: /<controller>/


        public async Task<IActionResult> SelectCategory(CancellationToken cancellation)
        {
            List<CategoryViewModel> categoryDtoModels =_mapper.Map<List<CategoryViewModel>>( await  _productAppService.GetCategories(cancellation));
            ViewBag.Massages = await _directOrderAppService.GetSellerComments(cancellation);
            return View("CategoryProduct" , categoryDtoModels);
        }

        public async Task<IActionResult> AddProduct(int id,CancellationToken cancellation)
        {
            await _productAppService.GetCategory(id, cancellation);
            ViewBag.Massages = await _directOrderAppService.GetSellerComments(cancellation);
            return View("AddProduct");
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(AddProductDto productDto,CancellationToken cancellation)
        {
            if(ModelState.IsValid)
            {
                await _productAppService.AddProduct(productDto, cancellation);
                return RedirectToAction("MainPage", "SellerManagement");
            }
            return View();
        }





        public async Task<IActionResult> ProductProfile(int id, CancellationToken cancellation)
        {
            DetailedProductDto detailedProduct = await _productAppService.GetProduct(id,cancellation);
            ViewBag.Massages = await _directOrderAppService.GetSellerComments(cancellation);
            return View(detailedProduct);
        }

        [HttpPost]
        public async Task<IActionResult> ProductProfile(DetailedProductDto productDto, CancellationToken cancellation)
        {
            if (await _productAppService.EditProduct(productDto,cancellation))
            {
                return RedirectToAction("ProductProfile", new { productDto.Id });
            }
            return View(productDto);
        }

        public async Task<IActionResult> DeleteProduct(int id, CancellationToken cancellation)
        {
            var DeactiveResult = await _productAppService.RemoveProduct(id, cancellation);
            if (DeactiveResult)
            {
                return RedirectToAction("ProductProfile", new { id });
            }
            return RedirectToAction("DeleteProduct", new { id });
        }


        public async Task<IActionResult> ActiveProduct(int id, CancellationToken cancellation)
        {
            await _productAppService.AcceptProduct(id, cancellation);
            return RedirectToAction("ProductProfile", new { id });
        }
        #endregion
    }
}

FinalProject_Market/Areas/Seller/Views/ProductManagement/AddProduct.cshtml
@model AddProductViewModel


<form id="uploadform" class="form-control" method="post" enctype="multipart/form-data">
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1"></span>
        <input type="text" class="form-control" placeholder="نام محصول" aria-label="Username" aria-describedby="basic-addon1" asp-for="ProductName">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text">$</span>
        <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" asp-for="Price">
        <span class="input-group-text">.00</span>
    </div>
    <div>
        <label for="formFileLg" class="form-label">Large file input example</label>
        <input multiple class="form-control form-control-lg" id="formFileLg" asp-for="fileImages" type="file">
    </div>
    <div class="input-group mb-3">
        <button type="submit" asp-controller="ProductManagement" asp-action="AddProduct" class="btn btn-primary mb-3">ثبت نهایی</button>
    </div>
</form>

FinalProject_Market/Areas/Seller/Views/ProductManagement/CategoryProduct.cshtml
@model List<CategoryViewModel>


<h1>دسته مورد نظر خود را انتخاب کنید. </h1>



@for (int i = 0; 2 * (i + 1) <= (int)(Model.Count() / 2) * 2; i++)
{
    <div class="container">
        <div class="d-inline-flex">
            <div class="card  m-3" style="width:min-content">
                <img class="card-img-top" src="/Images/Categories/@(Model[2*i].ImageFile)" alt="@Model[2 * i].Title" style="width:200px">
                <div class="card-body">

                    <a class="btn btn-primary" asp-route-id="@(Model[2*i].Id)" asp-controller="ProductManagement" asp-action="AddProduct">
                        <h5 class="card-title text-dark">@Model[2 * i].Title</h5>
                    </a>
                </div>
            </div>
            <div class="card  m-3" style="width:min-content">
                <img class="card-img-top" src="/Images/Categories/@(Model[2*i+1].ImageFile)" alt="@Model[2 * i+1].Title" style="width:200px">
                <div class="card-body">

                    <a class="btn btn-primary" asp-route-id="@(Model[2*i+1].Id)" asp-controller="ProductManagement" asp-action="AddProduct">
                        <h5 class="card-title text-dark">@Model[2 * i+1].Title</h5>
                    </a>
                </div>
            </div>
      
        </div>
    </div>

}

<div class="container">
    <div class="d-inline-flex" >
        @for (int i = 1; i <= Model.Count()% 2; i++)
        {
            <div class="card  m-3" style="width:min-content">
                <img class="card-img-top" src="/Images/Categories/@(Model[Model.Count()-i].ImageFile)" alt="@Model[Model.Count()-i].Title" style="width:200px">
                <div class="card-body">

                    <a class="btn btn-primary" asp-route-id="@(Model[Model.Count()-i].Id)" asp-controller="ProductManagement" asp-action="AddProduct">
                        <h5 class="card-title text-dark">@Model[Model.Count() - i].Title</h5>
                    </a>
                </div>
            </div>
        }
    </div>

</div>