FinalProject_Market/Areas/Seller/Controllers/PavilionManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppCore.DtoModels;
using AppCore.DtoModels.Product;
using AppService.Admin_;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FinalProject_Market.Areas.Admin.Controllers
{
    [Area("seller")]
    [Authorize(Roles ="seller")]
    public class PavilionManagementController : Controller
    {
        #region field
        private readonly IAccountAppServices _account;
        private readonly IMapper _mapper;
        private readonly IProductAppService _productAppService;
        private readonly IPavilionAppService _pavilionAppService;
        private readonly IDirectOrderAppService _directOrderAppService;
        #endregion

        #region ctor
        public PavilionManagementController(IAccountAppServices account,
            IMapper mapper, IProductAppService productAppService,
            IPavilionAppService pavilionAppService, IDirectOrderAppService directOrderAppService)
        {
            _account = account;
            _mapper = mapper;
            _productAppService = productAppService;
            _pavilionAppService = pavilionAppService;
            _directOrderAppService = directOrderAppService;
        }
        #endregion

        #region Implementation
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> PavilionProfile(int id, CancellationToken cancellation)
        {
            PavilionDtoModel detailedPavilion = await _pavilionAppService.GetPavilion(id, cancellation);
            ViewBag.Massages = await _directOrderAppService.GetSellerComments(cancellation);
            return View(detailedPavilion);
        }




        [HttpPost]
        public async Task<IActionResult> PavilionProfile(PavilionDtoModel productDto, CancellationToken cancellation)
        {
            if (await _pavilionAppService.EditPavilion(productDto, cancellation))
            {
                return RedirectToAction("PavilionProfile", new { productDto.Id });
            }
            return View(productDto);
        }

        public async Task<IActionResult> DeletePavilion(int id, CancellationToken cancellation)
        {
            var DeactiveResult = await _pavilionAppService.RemovePavilion(id, cancellation);
            if (DeactiveResult)
            {
                return RedirectToAction("PavilionProfile", new { id });
            }
            return RedirectToAction("DeletePavilion", new { id });
        }


        public async Task<IActionResult> ActivePavilion(int id, CancellationToken cancellation)
        {
            await _pavilionAppService.ActiveProduct(id, cancellation);
            return RedirectToAction("PavilionProfile", new { id });
        }


        #endregion

    }
}

FinalProject_Market/Areas/Seller/Controllers/SellerManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppCore;
using AppCore.DtoModels;
using AppCore.DtoModels.Auction;
using AppCore.DtoModels.Customer;
using AppCore.DtoModels.DirectOrder;
using AppCore.DtoModels.Product;
using AppCore.DtoModels.Seller;
using AppCore.DtoModels.User;
using AppService.Admin_;
using AutoMapper;
using FinalProject_Market.Areas.Admin.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FinalProject_Market.Areas.Seller.Controllers
{
    [Area("seller")]
    [Authorize(Roles ="seller")]
    public class SellerManagementController : Controller
    {
        #region field
        private readonly IPavilionAppService _pavilionService;
        private readonly IDirectOrderAppService _directOrderAppService;
        private readonly IAuctionAppService _auctionAppService;
        private readonly IAccountAppServices _accountAppService;
        private readonly IMapper _mapper;
        #endregion


        #region ctor
        public SellerManagementController(IPavilionAppService pavilionService, IAccountAppServices accountAppService, IMapper mapper, IAuctionAppService auctionAppService, IDirectOrderAppService directOrderAppService)
        {
            _pavilionService = pavilionService;
            _accountAppService = accountAppService;
            _mapper = mapper;
            _auctionAppService = auctionAppService;
            _directOrderAppService = directOrderAppService;
        }
        #endregion


        #region Implementation

        public async Task<IActionResult> MainPage(CancellationToken cancellation)
        {
            List<PavilionDtoModel> pavilionDtos = await _pavilionService.GetSellerPavilions(cancellation);
            ViewBag.Massages = await _directOrderAppService.GetSellerComments(cancellation);
            return View(pavilionDtos);
        }

        public async Task<IActionResult> GetProfile(CancellationToken cancellation)
        {
            Tuple<SellerOverViewDto, FullDetailSellerDto> sellerDto =await _accountAppService.GetCurrentUserProfile<FullDetailSellerDto>(cancellation);
            ViewBag.FullDetailSellerViewModel = sellerDto.Item1;
            ViewBag.Massages = await _directOrderAppService.GetSellerComments(cancellation);
            return View(sellerDto.Item2);
        }

        [HttpPost]
        public async Task<IActionResult> GetProfile(FullDetailSellerViewModel viewModel, CancellationToken cancellation)
        {
            var sellerDto = _mapper.Map<EditUserDto>(viewModel);
            var result = await _accountAppService.UpdateUser(sellerDto, cancellation);
            ViewBag.Massages = await _directOrderAppService.GetSellerComments(cancellation);
            return result ? RedirectToAction("GetProfile", new { viewModel.Id }) : View(viewModel);
        }

        public async Task<IActionResult> OrderHistory(CancellationToken cancellation)
        {
            ViewBag.Massages = await _directOrderAppService.GetSellerComments(cancellation);
            return View(new Tuple<List<DetailedDirctOrderDto>, List<DetailedAuctionDto>>(await _directOrderAppService.GetAllCurrentUserPaidDirectOrders(cancellation), await _auctionAppService.GetAllPaidAuctions(cancellation)));
        }
        #endregion


    }
}

FinalProject_Market/Areas/Seller/Views/SellerManagement/GetProfile.cshtml
@{
    Layout = "_Layout.cshtml";
}
@using AppCore.DtoModels.Seller;


@model  FullDetailSellerDto



<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            پروفایل کاربری
        </h1>

    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-md-3">

                <!-- Profile Image -->
                <div class="box box-primary">
                    <div class="box-body box-profile">
                        <img class="profile-user-img img-responsive img-circle" src="~/images/UserImages/@Model.FilePathSource" alt="User profile picture">

                        <h3 class="profile-username text-center">@ViewBag.FullDetailSellerViewModel.FullName</h3>
                        @if (ViewBag.FullDetailSellerViewModel.HasMedal)
                        {
                            <i class='fas fa-medal' style='font-size:48px;color:red'></i>
                        }

                        <ul class="list-group list-group-unbordered">
                            <li class="list-group-item">
                                <b>سفارش های موفق</b> <a class="pull-left">@ViewBag.FullDetailSellerViewModel.CompletedOrderNumber</a>
                            </li>
                            <li class="list-group-item">
                                <b>مزایده های برگذار شده</b> <a class="pull-left">@ViewBag.FullDetailSellerViewModel.CompletedAuctionNumber</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
                <!-- About Me Box -->
                <!-- /.box -->
            </div>
            <!-- /.col -->
            <!-- /.col -->
        </div>
        <!-- /.row -->

    </section>

    <div class="card card-info justify-content-center ">
        <div class="card-header">
            <h3 class="card-title">مشخصات</h3>
        </div>
        <form class="card-body" method="post" enctype="multipart/form-data" role="form">
            @*<div class="input-group mb-3">*@
                @*<div class="input-group-prepend">
                    <span class="input-group-text">آیدی</span>
                </div>*@

                <input type="number" class="form-control" asp-for="@Model.Id" hidden>
            @*</div>*@
            <div class="input-group mb-3">
                <img src="~/images/UserImages/@Model.FilePathSource" class="avatar img-circle img-thumbnail" alt="avatar">
                <label for="formFileLg" class="form-label">تغییر عکس</label>
                <input multiple class="form-control form-control-lg" id="formFileLg" asp-for="UserFile" type="file">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">نام</span>
                </div>
                <input type="text" class="form-control" asp-for="@Model.FirstName" placeholder="نام ">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">نام خانوادگی</span>
                </div>
                <input type="text" class="form-control" asp-for="@Model.LastName" placeholder="نام خانوادگی">
            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                </div>
                <input type="email" class="form-control" asp-for="@Model.Email" placeholder="ایمیل">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-phone"></i></span>
                </div>
                <input type="text" class="form-control " asp-for="@Model.PhoneNumber" placeholder="شماره همراه">
            </div>
            <!-- /.row -->
            <!-- /input-group -->

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <button type="submit" class="btn btn-danger" asp-controller="SellerManagement" asp-action="GetProfile">ویرایش</button>

                </div>


            </div>


        </form>

    </div>
    <!-- /.content -->
</div>

FinalProject_Market/Areas/Seller/Views/SellerManagement/MainPage.cshtml
@using AppCore.DtoModels;
@model List<PavilionDtoModel>


@{
    Layout = "_Layout.cshtml";
}
<h1>فروشگاه های من</h1>
@foreach (PavilionDtoModel pavilionDto in Model)
{
    <div style="width:360px;display:flex" class="jsx-b2349dd13b8a662b">
        <div class="jsx-b2349dd13b8a662b logo">
            <img src="~/images/@pavilionDto.ImageFile" style="width:64px;height:auto;" alt="@pavilionDto.Title" class="jsx-b2349dd13b8a662b">
        </div>
        <div class="jsx-b2349dd13b8a662b title">
            <a class="btn" asp-area="Seller" asp-controller="PavilionManagement" asp-action="PavilionProfile" asp-route-id="@pavilionDto.Id">
                <h1 class="jsx-b2349dd13b8a662b">@pavilionDto.Title</h1>
            </a>
        </div>
    </div>

}

FinalProject_Market/Areas/Seller/Views/SellerManagement/OrderHistory.cshtml
@using AppCore.DtoModels.Auction;
@using AppCore.DtoModels.DirectOrder;

@model Tuple<List<DetailedDirctOrderDto>, List<DetailedAuctionDto>>



<div class="container">
    <!-- /.row -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">جدول مزایده ها</h3>

                    <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control float-right" placeholder="جستجو">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover">
                        <tr>
                            <th>شماره</th>
                            <th>تاریخ شروع مزایده</th>
                            <th>تاریخ پایان مزایده</th>
                            <th>برنده مزایده</th>
                            <th>قیمت نهایی</th>
                            <th>مشاهده نظرات و کارمزد </th>
                            <th>محصولات</th>

                        </tr>
                        @foreach (var auction in Model.Item2)
                        {
                            @if (auction.IsFinished == true)

                            {
                                <tr>
                                    <td>@auction.Id</td>
                                    <td>@auction.StartTime</td>
                                    <td>@auction.EndTime</td>
                                    <td>@auction.AcceptedCustomerName</td>
                                    <td>@auction.FinalPrice</td>
                                    <td>
                                        <a id="myBtn" class="btn btn-primary" data-toggle="modal" data-target="#modalpopup_@auction.Id">مشاهده جزییات</a>
                                        <div class="modal" id="modalpopup_@auction.Id">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h3>سود بدست آمده از این معامله: @auction.ComissionPaidByauction</h3>
                                                    </div>



                                                    <!-- Modal body -->
                                                    <div class="modal-body">
                                                        <div class="container">
                                                            @if (auction.IsCommentDeleted==false && auction.IsCommentAcceptedByAdmin==true)
                                                            {
                                                                <div class="d-flex justify-content-around">
                                                                    <div>
                                                                        <h4 class="modal-title">
                                                                            @auction.FinalCommentByCostumer
                                                                        </h4>
                                                                    </div>
                                                                </div>
                                                            }

                                                        </div>

                                                    </div>

                                                    <!-- Modal footer -->
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>



                                    </td>

                                    <td>
                                        <table>
                                            <tbody>
                                                <tr>
                                                    @foreach (var product in auction.ProductDtos)
                                                    {
                                                        <td>@product.ProductName</td>
                                                    }
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>

                            }
                        }



                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div><!-- /.row -->
</div>

<div class="container">
    <!-- /.row -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">جدول سفارشات مستقیم</h3>

                    <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control float-right" placeholder="جستجو">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover">
                        <tr>
                            <th>شماره</th>
                            <th>قیمت نهایی</th>
                            <th>خریدار</th>
                            <th>مشاهده نظرات و کارمزد </th>
                            <th>محصولات</th>


                        </tr>
                        @foreach (var directOrder in Model.Item1)
                        {
                  
                                <tr>
                                    <td>@directOrder.Id</td>
                                    <td>@directOrder.TotalPrice</td>
                                    <td>@directOrder.CustomerName</td>
                                    <td>
                                        <a id="myBtn" class="btn btn-primary" data-toggle="modal" data-target="#modalpopup_@directOrder.Id">مشاهده جزییات</a>
                                        <div class="modal" id="modalpopup2_@directOrder.Id">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h3>سود بدست آمده از این معامله: @directOrder.ComissionPaidByOrder</h3>
                                                    </div>



                                                    <!-- Modal body -->
                                                    <div class="modal-body">
                                                        <div class="container">
                                                            @if (directOrder.IsCommentDeleted != false && directOrder.IsCommentAcceptedByAdmin == true)
                                                            {
                                                                <div class="d-flex justify-content-around">
                                                                    <div>


                                                                        <h4 class="modal-title">
                                                                            @directOrder.CommentByCostumer
                                                                        </h4>
                                                                    </div>


                                                                </div>
                                                            }


                                                        </div>

                                                    </div>

                                                    <!-- Modal footer -->
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <table>
                                            <tbody>
                                                <tr>
                                                    @foreach (var product in directOrder.ProductDtos)
                                                    {
                                                        <td>@product.ProductName</td>
                                                    }
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>

                        }



                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div><!-- /.row -->
</div>


<!-- The Modal -->